FROM  node:22-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm ci 

COPY . .

RUN npm run build

FROM node:22-alpine AS runner 

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist

EXPOSE 3000

USER node

ENTRYPOINT ["node"]

CMD ["dist/server.js"]
