name: 02 -Manual

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Nivel de log"
        required: true
        default: "info"
        type: choice
        options:
          - info
          - debug
          - warn
          - error

      environment:
        description: "Entorno"
        type: environment

      dry_run:
        description: "Ejecutar sin aplicar los cambios"
        required: false
        default: false
        type: boolean

      reason:
        description: "Motivo de la ejecución"
        required: false
        default: "Ejecución manual"
        type: string

jobs:
  manual:
    runs-on: ubuntu-24.04
    steps:
      - name: Mostrar todos los inputs
        env:
          LOG_LEVEL: ${{inputs.log_level}}
          ENVIRONMENT: ${{inputs.environment}}
          DRY_RUN: ${{inputs.dry_run}}
          REASON: ${{inputs.reason}}
        run: |
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "DRY_RUN: $DRY_RUN"
          echo "REASON: $REASON"

      - name: Deploy (solo si NO es dry-run)
        if: ${{!inputs.dry_run}}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Desplegando a $ENVIRONMENT"

      - name: Solo Log (si es dry-run)
        if: ${{ inputs.dry_run }}
        run: |
          echo: "Dry Run: No se han aplicado los cambios"
