name: 04 - Events

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:

jobs:
  inspect-event:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - name: Inspect Event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Issue: ${{ github.event.issue.number }}"
          echo "Comment: ${{ github.event.comment.body }}"

      - name: Comentar como bot en Github Actions
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_REPOSITORY: ${{ github.repository }}
        run: gh issue comment "$ISSUE_NUMBER" --body "Gracias por tu aporte. Nos pondremos en contacto contigo lo antes posible! 🏃" --repo "$GH_REPOSITORY"
