name: 05 - CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Lint
        run: pnpm lint:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Lint
        run: pnpm lint:backend

  frontend-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Test
        run: pnpm test:frontend

  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Test
        run: pnpm test:backend
