name: 05 - CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd

      - name: Lint
        run: pnpm lint:frontend

  frontend-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-latest]
        node-version: [22, 24]
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd
          node-version: ${{ matrix.node-version }}

      - name: Test ${{ matrix.os }} - Node.js v${{ matrix.node-version }}
        run: pnpm test:frontend

  frontend-build:
    needs: [frontend-lint, frontend-test]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd

      - name: Build
        run: pnpm build:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd

      - name: Lint
        run: pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd

      - name: Test
        run: pnpm test:backend

  backend-build:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          working-directory: 12-ejercicio-cicd

      - name: Build
        run: pnpm build:backend
