name: opencode review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  opencode:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Check credentials
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
        run: |
          if [[ -z "$OPENCODE_API_KEY" ]]; then
            echo "::warning::No se ha encontrado la API Key para Opencode. Se omitirá responder a Issues o Comentarios"
            exit 0
          fi
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
        with:
          model: opencode/big-pickle
          prompt: |
            Review this pull request:
            - Check for code quality issues
            - Look for potential bugs
            - Suggest improvements
